name: Furnace CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Bootstrap test environment
      run: |
        sudo apt update
        sudo apt install debootstrap python3-venv make
        python -m pip install --upgrade pip
        make dev
    - name: Lint
      run: |
        make cs
        make lint
    - name: Test
      run: |
        make check
